<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="5CD93439TM" failures="2" tests="8" name="RetryMulitpleFailedTestCases" time="0.081" errors="0" timestamp="2021-11-28T15:56:05 IST">
  <testcase classname="mytests.MyTests" name="Test1" time="0.012">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test1" time="0.001">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test1" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test1(MyTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.001">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="mytests.MyTests" name="Test2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTests.Test2(MyTests.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMulitpleFailedTestCases -->
